version: "3.7"

networks:
  simple-network:
    driver: bridge

services:

  proxy:
    image: jonasal/nginx-certbot:latest
    container_name: proxy
    environment:
      CERTBOT_EMAIL: "shard.f@mail.ru"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - "simple-network"
    volumes:
      - ./certificates:/etc/letsencrypt
      - ./proxy/user_conf.d:/etc/nginx/user_conf.d

  api:
    image: api:latest
    container_name: api
    build:
      context: ./src
      dockerfile: ./Sample.Server/Dockerfile
    expose:
      - "5000"
    restart: always
    depends_on:
      - database
    networks:
      - "simple-network"
    volumes:
      - "./logs:/app/logs"

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./postgresdata:/var/lib/postgresql/data"