version: "3.7"

networks:
  simple-network:
    driver: bridge

services:

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: proxy
    restart: unless-stopped
    environment:
        CERTBOT_EMAIL: "shard.f@mail.ru"
    ports:
        - 80:80
        - 443:443
    networks:
        - "simple-network"
    volumes:
        - ./certificates:/etc/letsencrypt
        - ./proxy/user_conf.d:/etc/nginx/user_conf.d

  api:
    image: api:latest
    container_name: api
    build:
        context: ./src
        dockerfile: ./Sample.Server/Dockerfile.Long
    expose:
        - "5000"
    depends_on:
        - proxy
        - database
    networks:
        - "simple-network"
    restart: always

  database:
    image: postgres:latest
    container_name: database
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    ports: 
        - "5432:5432"
    volumes:
        - "./simpledata:/var/lib/postgresql/data"